void knight_chess();
void boxes_task();
int find_last_simple(int limit);
int find_last_simple_static(int limit);
int min_divisor(int n);
int min_distance();
void square_equation();
void equation_system();
void check_mapping(int n, int mod = INT_MAX);
int64_t rand_int(int64_t start, int64_t end);